### ISSUE TITLE
9:26启动策略报 signed integer greater than maximum错误

### ISSUE THREAD

**Issue by handsomu** [ricequant/rqalpha-mod-vnpy#23]
`
`
Traceback (most recent call last):
  File "/media/psf/Home/rqalpha/rqalpha/main.py", line 289, in run
    Executor(env).run(bar_dict)
    │        │        └ BarMap(RB1710)
    │        └ <rqalpha.environment.Environment object at 0x7f11239a7410>
    └ <class 'rqalpha.core.executor.Executor'>
  File "/media/psf/Home/rqalpha/rqalpha/core/executor.py", line 52, in run
    for event in self._env.event_source.events(start_date, end_date, frequency):
  File "/media/psf/Home/rqalpha-mod-vnpy/rqalpha_mod_vnpy/vnpy_event_source.py", line 131, in events
    calendar_dt = parse(''.join((str(tick.date), str(tick.time/1000))))
                  │                  │               └ {'b5_v': 0, 'b4_v': 0, 'limit_down': 2796.0, 'limit_up': 3217.0, 'high': 2954.0, 'b5': 1.7976931348623157e+308, 'b3_v': 0, 'b1':...
                  │                  └ {'b5_v': 0, 'b4_v': 0, 'limit_down': 2796.0, 'limit_up': 3217.0, 'high': 2954.0, 'b5': 1.7976931348623157e+308, 'b3_v': 0, 'b1':...
                  └ <function parse at 0x7f111c960b18>
  File "/home/cui/anaconda2/envs/rqa/lib/python2.7/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
           │                   │          └ {}
           │                   └ '2017050592628'
           └ <dateutil.parser.parser object at 0x7f111ce79050>
  File "/home/cui/anaconda2/envs/rqa/lib/python2.7/site-packages/dateutil/parser.py", line 578, in parse
    if cday > monthrange(cyear, cmonth)[1]:
  File "/home/cui/anaconda2/envs/rqa/lib/python2.7/calendar.py", line 121, in monthrange
    day1 = weekday(year, month, 1)
           │       │     └ 5
           │       └ 2017050592628
           └ <function weekday at 0x7f111c956758>
  File "/home/cui/anaconda2/envs/rqa/lib/python2.7/calendar.py", line 113, in weekday
    return datetime.date(year, month, day).weekday()
           │             │     │      └ 1
           │             │     └ 5
           │             └ 2017050592628
           └ <module 'datetime' from '/home/cui/anaconda2/envs/rqa/lib/python2.7/lib-dynload/datetime.so'>
OverflowError: signed integer is greater than maximum
2017-05-05 09:26:28.00 ERROR signed integer is greater than maximum
[2017-05-05 09:26:31.950227] ERROR: system_log: 策略运行产生异常
Traceback (most recent call last):
  File "/media/psf/Home/rqalpha/rqalpha/main.py", line 289, in run
    Executor(env).run(bar_dict)
  File "/media/psf/Home/rqalpha/rqalpha/core/executor.py", line 52, in run
    for event in self._env.event_source.events(start_date, end_date, frequency):
  File "/media/psf/Home/rqalpha-mod-vnpy/rqalpha_mod_vnpy/vnpy_event_source.py", line 131, in events
    calendar_dt = parse(''.join((str(tick.date), str(tick.time/1000))))
  File "/home/cui/anaconda2/envs/rqa/lib/python2.7/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/cui/anaconda2/envs/rqa/lib/python2.7/site-packages/dateutil/parser.py", line 578, in parse
    if cday > monthrange(cyear, cmonth)[1]:
  File "/home/cui/anaconda2/envs/rqa/lib/python2.7/calendar.py", line 121, in monthrange
    day1 = weekday(year, month, 1)
  File "/home/cui/anaconda2/envs/rqa/lib/python2.7/calendar.py", line 113, in weekday
    return datetime.date(year, month, day).weekday()
OverflowError: signed integer is greater than maximum
`

`

**Comment by Cuizi7** [comment]
feature/abandon-vnpy-gateway 分支已修复

**Comment by Cuizi7** [comment]
master 分支已修复。
