### ISSUE TITLE
最新版本rqalpha 出错 ImportError: No module named account

### ISSUE THREAD

**Issue by conglin** [ricequant/rqalpha-mod-vnpy#25]
2017-07-01 07:24:33.00 ERROR No module named account
[2017-07-01 07:24:33.068771] ERROR: system_log: 策略运行产生异常
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/rqalpha/main.py", line 195, in run
    mod_handler.start_up()
  File "//anaconda/lib/python2.7/site-packages/rqalpha/mod/__init__.py", line 68, in start_up
    self._mod_dict[mod_name].start_up(self._env, mod_config)
  File "//anaconda/lib/python2.7/site-packages/rqalpha_mod_vnpy/mod.py", line 34, in start_up
    from .vnpy_broker import VNPYBroker
  File "//anaconda/lib/python2.7/site-packages/rqalpha_mod_vnpy/vnpy_broker.py", line 20, in <module>
    from rqalpha.model.account import BenchmarkAccount, FutureAccount
ImportError: No module named account

**Comment by conglin** [comment]
@Cuizi7

**Comment by conglin** [comment]
安装哪个rqalpha 版本能运行？ ubuntu中的image是哪个版本？

**Comment by Cuizi7** [comment]
vnpy mod已不再维护。不适配新版本rqalpha 和 vnpy。
欢迎移步至 https://github.com/ricequant/rqalpha-mod-ctp

**Comment by conglin** [comment]
谢谢 快速回复 :)
