### ISSUE TITLE
ImportError: No module named account

### ISSUE THREAD

**Issue by FallacyWalker** [ricequant/rqalpha-mod-vnpy#27]
rqalpha : 3.0.2 
rqalpha-mod-vnpy: 0.9.30
vnpy is also the latest;

/usr/bin/python2.7 /home/walker/Desktop/Rqalpha30/rqalpha/startmod.py
Traceback (most recent call last):
  File "/home/walker/Desktop/Rqalpha30/rqalpha/rqalpha/main.py", line 195, in run
    mod_handler.start_up()
    └ <rqalpha.mod.ModHandler object at 0x7faba6b47f90>
  File "/home/walker/Desktop/Rqalpha30/rqalpha/rqalpha/mod/__init__.py", line 68, in start_up
    self._mod_dict[mod_name].start_up(self._env, mod_config)
    │              │                  │          └ {'CTP': {'brokerID': '9999',
 'mdAddress': 'tcp://180.168.146.187:10010',
 'password': 'FinalicA_0472',
 'tdAddress': 'tcp://180...
    │              │                  └ <rqalpha.mod.ModHandler object at 0x7faba6b47f90>
    │              └ u'vnpy'
    └ <rqalpha.mod.ModHandler object at 0x7faba6b47f90>
  File "/usr/local/lib/python2.7/dist-packages/rqalpha_mod_vnpy/mod.py", line 34, in start_up
    from .vnpy_broker import VNPYBroker
  File "/usr/local/lib/python2.7/dist-packages/rqalpha_mod_vnpy/vnpy_broker.py", line 20, in <module>
    from rqalpha.model.account import BenchmarkAccount, FutureAccount
ImportError: No module named account
2017-08-07 ERROR No module named account
[2017-08-07 11:27:55.326767] ERROR: system_log: 策略运行产生异常
Traceback (most recent call last):
  File "/home/walker/Desktop/Rqalpha30/rqalpha/rqalpha/main.py", line 195, in run
    mod_handler.start_up()
  File "/home/walker/Desktop/Rqalpha30/rqalpha/rqalpha/mod/__init__.py", line 68, in start_up
    self._mod_dict[mod_name].start_up(self._env, mod_config)
  File "/usr/local/lib/python2.7/dist-packages/rqalpha_mod_vnpy/mod.py", line 34, in start_up
    from .vnpy_broker import VNPYBroker
  File "/usr/local/lib/python2.7/dist-packages/rqalpha_mod_vnpy/vnpy_broker.py", line 20, in <module>
    from rqalpha.model.account import BenchmarkAccount, FutureAccount
ImportError: No module named account
Traceback (most recent call last):
  File "/home/walker/Desktop/Rqalpha30/rqalpha/startmod.py", line 78, in <module>
    run_file(strategy_file_path, config_mod1)
    │        │                   └ {'base': {'accounts': {'future': 100000}, 'start_date': '2016-01-01', 'end_date': '2016-12-01', 'strategy_file': '/home/walker/D...
    │        └ '/home/walker/Desktop/Rqalpha30/rqalpha/rqalpha/examples/buy_and_hold.py'
    └ <function run_file at 0x7faba71fcc80>
  File "/home/walker/Desktop/Rqalpha30/rqalpha/rqalpha/__init__.py", line 97, in run_file
    return main.run(config)
           │        └ {'base': {'accounts': {'FUTURE': 100000.0},
 'benchmark': None,
 'data_bundle_path': '/home/walker/.rqalpha/bundle',
 'end_date'...
           └ <module 'rqalpha.main' from '/home/walker/Desktop/Rqalpha30/rqalpha/rqalpha/main.pyc'>
  File "/home/walker/Desktop/Rqalpha30/rqalpha/rqalpha/main.py", line 317, in run
    mod_handler.tear_down(code, user_exc)
    │                     │     └ CustomException()
    │                     └ EXIT_CODE.EXIT_INTERNAL_ERROR
    └ <rqalpha.mod.ModHandler object at 0x7faba6b47f90>
  File "/home/walker/Desktop/Rqalpha30/rqalpha/rqalpha/mod/__init__.py", line 73, in tear_down
    ret = self._mod_dict[mod_name].tear_down(*args)
    │     │              │                    └ (EXIT_CODE.EXIT_INTERNAL_ERROR, CustomException())
    │     │              └ u'vnpy'
    │     └ <rqalpha.mod.ModHandler object at 0x7faba6b47f90>
    └ None
  File "/usr/local/lib/python2.7/dist-packages/rqalpha_mod_vnpy/mod.py", line 55, in tear_down
    self._gateway.exit()
    └ <rqalpha_mod_vnpy.mod.VNPYMod object at 0x7faba6b35f10>
AttributeError: 'NoneType' object has no attribute 'exit'

Process finished with exit code 1

**Comment by conglin** [comment]
这个不再维护了 看我这个issue  https://github.com/ricequant/rqalpha-mod-vnpy/issues/25
