### ISSUE TITLE
运行vnpy mod时报错

### ISSUE THREAD

**Issue by FallacyWalker** [ricequant/rqalpha-mod-vnpy#3]
rqalpha version: 2.0.7
rqalpha_mod_vnpy version: 0.9.11
使用pycharm运行；

今天又没有这个错误了 。 

Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\APPS\Anaconda4_32\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\APPS\Anaconda4_32\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\vnpy\vn.trader\eventEngine.py", line 218, in __run
    self.__process(event)
  File "C:\vnpy\vn.trader\eventEngine.py", line 228, in __process
    [handler(event) for handler in self.__handlers[event.type_]]
  File "C:\LocalRqalpha\rqalpha\rqalpha\mod\rqalpha_mod_vnpy\vnpy_engine.py", line 254, in <lambda>
    self.event_engine.register(EVENT_ERROR, lambda e: system_log.error(e['data']))
AttributeError: Event instance has no attribute '__getitem__'

**Comment by Cuizi7** [comment]
麻烦您贴一下 rqalpha 的版本以及 rqalpha-mod-vnpy 的版本。

**Comment by FallacyWalker** [comment]
issue已更新；

**Comment by Cuizi7** [comment]
那暂时 close了，如果之后再遇到相同的问题可以先尝试删掉 .rqalpha 文件夹下的配置文件。
