### ISSUE TITLE
我运行vnpy mod报错，具体信息如下：

### ISSUE THREAD

**Issue by FallacyWalker** [ricequant/rqalpha-mod-vnpy#5]
OS: Ubuntu 16.04
Python 2.7.12
rqalpha-mod-vnpy: 0.9.11
rqalpha: 2.0.9

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/Vnpy/vnpy/vn.trader/eventEngine.py", line 218, in __run
    self.__process(event)
  File "/home/Vnpy/vnpy/vn.trader/eventEngine.py", line 228, in __process
    [handler(event) for handler in self.__handlers[event.type_]]
  File "/home/RqalphaNew/rqalpha/rqalpha/mod/rqalpha_mod_vnpy/vnpy_engine.py", line 254, in <lambda>
    self.event_engine.register(EVENT_ERROR, lambda e: system_log.error(e['data']))
AttributeError: Event instance has no attribute '__getitem__'

Traceback (most recent call last):
  File "/home/RqalphaNew/rqalpha/rqalpha/main.py", line 191, in run
    mod_handler.start_up()
    └ <rqalpha.mod.ModHandler object at 0x7fb9c50f63d0>
  File "/home/RqalphaNew/rqalpha/rqalpha/mod/__init__.py", line 67, in start_up
    self._mod_dict[mod_name].start_up(self._env, mod_config)
    │              │                  │          └ {'commission_multiplier': 1,
 'enabled': True,
 'matching_type': MATCHING_TYPE.CURRENT_BAR_CLOSE,
 'price_limit': True,
 'signal...
    │              │                  └ <rqalpha.mod.ModHandler object at 0x7fb9c50f63d0>
    │              └ 'sys_simulation'
    └ <rqalpha.mod.ModHandler object at 0x7fb9c50f63d0>
  File "/home/RqalphaNew/rqalpha/rqalpha/mod/rqalpha_mod_sys_simulation/mod.py", line 47, in start_up
    raise RuntimeError(_("Not supported matching type {}").format(mod_config.matching_type))
                       │                                          └ {'commission_multiplier': 1,
 'enabled': True,
 'matching_type': MATCHING_TYPE.CURRENT_BAR_CLOSE,
 'price_limit': True,
 'signal...
                       └ <function gettext at 0x7fb9d118c9b0>
RuntimeError: 不支持撮合类型: MATCHING_TYPE.CURRENT_BAR_CLOSE
0000-00-00 ERROR 不支持撮合类型: MATCHING_TYPE.CURRENT_BAR_CLOSE
[2017-04-11 16:01:00.747647] ERROR: system_log: 策略运行产生异常
Traceback (most recent call last):
  File "/home/RqalphaNew/rqalpha/rqalpha/main.py", line 191, in run
    mod_handler.start_up()
  File "/home/RqalphaNew/rqalpha/rqalpha/mod/__init__.py", line 67, in start_up
    self._mod_dict[mod_name].start_up(self._env, mod_config)
  File "/home/RqalphaNew/rqalpha/rqalpha/mod/rqalpha_mod_sys_simulation/mod.py", line 47, in start_up
    raise RuntimeError(_("Not supported matching type {}").format(mod_config.matching_type))
RuntimeError: 不支持撮合类型: MATCHING_TYPE.CURRENT_BAR_CLOSE

**Comment by FallacyWalker** [comment]
不好意思，提重了，不过Ubuntu上 .rqalpha文件夹下没有找到配置文件；

**Comment by Cuizi7** [comment]
File "/home/RqalphaNew/rqalpha/rqalpha/mod/rqalpha_mod_vnpy/vnpy_engine.py", line 254, in 
self.event_engine.register(EVENT_ERROR, lambda e: system_log.error(e['data']))
AttributeError: Event instance has no attribute 'getitem'

这个错误已在 0.9.13 中修复

**Comment by Cuizi7** [comment]
另外目前运行 vnpy mod 需要手动关闭 simulation mod

**Comment by snowzane** [comment]
@Cuizi7 我觉得vnpy-mod 运行时应该检测冲突Mod是否开启，如果开启的话，给一个提示，然后退出。这样比较好。

**Comment by Cuizi7** [comment]
@wh1100717 好的，之后加入这个功能。

**Comment by hzliu** [comment]
优先级设置的比 simulation 低是不是就可以了？

2017-04-13 10:50 GMT+08:00 Cuizi7 <notifications@github.com>:

**Comment by FallacyWalker** [comment]
如何手动关闭simulation mod 呢 ？

**Comment by snowzane** [comment]
@FallacyWalker http://rqalpha.io/zh_CN/latest/#mod

**Comment by FallacyWalker** [comment]
不支持撮合类型的错误是bug吗？
